### ISSUE TITLE
Fingerprints?

### ISSUE THREAD

**Issue by chocol4te** [dignifiedquire/pgp#1]
Hello,

In the current implementation is there any way of retrieving the fingerprint from a public key?

Can signatures be read, added and removed? I can't find much on Docs.rs but the current codebase is newer.

Thanks!

**Comment by dignifiedquire** [comment]
Hey, thanks for your interest. Unfortunately the project is not quite there yet. Parsing things mostly works, with some additional handling required to ignore malformed input. So there is currently no way to generate the fingerprint to a public key. If the data is parsed, signatures could be read, but not modified currently

**Comment by chocol4te** [comment]
No problem, thanks so much! I’d be happy to try and contribute if you wouldn’t mind roughly what needs to be done :)

**Comment by dignifiedquire** [comment]
So many things that need doing, but some things are there :) 

I just finished the first pass for parsing, so armor'ed and raw bytes can be now parsed for keys. The highlevel api can be found in `src/key.rs`

The next step would be adding read fingerprint support under a `fingerprint` method on the `Key` type I would say, which generates the fingerprint according to the spec, delegating the actual work to the `primary_key`. 

Rough next things I want to make happen would be
- parsing (most things are there in terms of raw packets, but now they need assembling)
  - implement private key parsing
  - implement message parsing, 
  - implement detached signature parsing,
- reading
  - ensure keys are usable with openssl
  - signature validation
  - message decryption + decompression
- storing
  - implement a persistent key store (not sure with what backend yet)
  - key import & export
- writing
  - generate keys
  - sign 
  - encrypt
  - serialize to bytes
  - serialize to armor'ed ascii

**Comment by dignifiedquire** [comment]
Yes please, I know V3 keys are not great, but I want to be able to handle the whole RFC eventually, and leave it up to more users of the library which versions they allow and accept.

**Comment by chocol4te** [comment]
Sure thing, do you have any preference on crates for hashing functions? I'm partial to https://github.com/RustCrypto/hashes but I can use whatever you prefer.

**Comment by dignifiedquire** [comment]
I have already added openssl as a crate, so lets use that for now. Eventually I would love to see all crypto in rust, but given the amount of algorithms that need support going with openssl for now seems like a good choice.

**Comment by chocol4te** [comment]
Definitely. It would be really nice to have it as a pure Rust crate, so can be used in completely static binaries. All other PGP crates right now can't be used for `x86_64-unknown-linux-musl` in a scratch docker container.

**Comment by dignifiedquire** [comment]
This looks like it should do the trick and does support openssl https://github.com/emk/rust-musl-builder

Disclaimer: I have pretty much no experience building anything for musl

**Comment by dignifiedquire** [comment]
best way I think for now is to 
- add a fingerprint method on composed/key that simply calls primarykey.fingerprint
- add the actual fingerprint impl in https://github.com/dignifiedquire/pgp/blob/master/src/packet/types/key.rs 
- the details on the type references in there I am not quite sure yet, will post in a bit

**Comment by dignifiedquire** [comment]
I think dou can implement it like algorithm is implemented, proxy_call for exposing at the key level and adding it in the key macro

**Comment by dignifiedquire** [comment]
also, sorry for the complex types but that is the best way I found so far to encode as much info as possible in the typesystem without resorting to tons of dynamic dispatches

**Comment by chocol4te** [comment]
I have everything in `fingerprint()` working for V4 and V3/2, except for creation times. Adding a `creation_time: u32` to  the `Key` struct seems problematic and incorrect, additionally, I have never used nom before so I made a mess of the parsing macros. 

Is there another type-encoded format for using internally, like transferrable public keys?

**Comment by chocol4te** [comment]
Done. https://github.com/dignifiedquire/pgp/pull/5
